In [8]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

dat = "/gpfs/commons/home/ssowinski/sc-splicing/platform_comp/leaflet_split/intron_clusters.gz"
df = pd.read_csv(dat, sep="}")

/scratch/ipykernel_39138/976749066.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dat, sep="}")

In [9]:
df.head()

,chrom,chromStart,chromEnd,name,score,strand,thickStart,thickEnd,itemRgb,blockCount,...,num_cells_wjunc,cell_readcounts,block_add_start,block_subtract_end,intron_length,cell_type,junction_id,Cluster,gene_id,Count
0,1,17055,17232,JUNC000000130,121,-,16944,17263,"255,0,0",2,...,92,"07_1_10_30:1,07_38_36_26:3,07_24_43_92:1,07_10...",111,31,177,sample7_cell,1_17055_17232,9994,ENSG00000227232.5,4
1,1,17055,17605,JUNC000000140,9,-,16950,17707,"255,0,0",2,...,8,"07_43_49_77:1,07_38_13_81:1,07_10_60_95:1,07_1...",105,102,550,sample7_cell,1_17055_17605,9994,ENSG00000227232.5,4
2,1,17055,17914,JUNC000000170,9,-,16955,17971,"255,0,0",2,...,6,"07_48_2_17:1,07_36_23_31:2,07_38_12_40:1,07_19...",100,57,859,sample7_cell,1_17055_17914,9994,ENSG00000227232.5,4
3,1,17368,17605,JUNC000000200,72,-,17276,17715,"255,0,0",2,...,33,"07_28_67_65:2,07_39_18_71:2,07_26_45_58:2,07_2...",92,110,237,sample7_cell,1_17368_17605,9994,ENSG00000227232.5,4
4,1,146509,146641,JUNC000000860,8,-,146408,146750,"255,0,0",2,...,4,"07_48_41_65:1,07_12_43_37:2,07_34_27_55:4,07_3...",101,109,132,sample7_cell,1_146509_146641,10087,ENSG00000241860.7,2

In [10]:
df.cell_type.unique()

array(['sample7_cell', 'sample6_cell', 'sample1_cell', 'sample3_cell',
       'sample8_cell', 'sample5_cell', 'sample2_cell', 'sample4_cell'],
      dtype=object)

In [12]:
cells = df[["cell_readcounts", "cell_type"]].drop_duplicates()
cells.head()
chunk = cells.copy()

In [13]:
chunk['cell_readcounts'] = chunk['cell_readcounts'].str.split(',')
chunk = chunk.explode('cell_readcounts')
chunk[['cell', 'junc_count']] = chunk['cell_readcounts'].str.split(pat=':', n=1, expand=True)
chunk = chunk.drop(['cell_readcounts'], axis=1)

In [15]:
chunk["cell_id"] = chunk.cell + "_" + chunk.cell_type
chunk.head()

      cell_type         cell junc_count                   cell_id
0  sample7_cell   07_1_10_30          1   07_1_10_30_sample7_cell
0  sample7_cell  07_38_36_26          3  07_38_36_26_sample7_cell
0  sample7_cell  07_24_43_92          1  07_24_43_92_sample7_cell
0  sample7_cell  07_10_37_81          1  07_10_37_81_sample7_cell
0  sample7_cell  07_36_16_82          1  07_36_16_82_sample7_cell

In [16]:
len(chunk.cell_id.unique())

1563119